language: c

env:
    global: HOMEBREW_NO_AUTO_UPDATE=1

compiler:
    - gcc
    - clang

os:
    - osx
    - linux

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew bundle --file=.Brewfile; fi

addons:
    apt:
        packages:
        - ninja-build
        #- gcc-mingw-w64-i686
        #- libz-mingw-w64-dev
        #- nsis
        - liblua5.1-dev
        - liblua5.2-dev
        #- liblua5.3-dev
        #- libluajit5.1-dev

script:
    - make -j4 dev
